import { create } from 'zustand'

const translations = {
  en: {
    dashboard: 'Dashboard',
    vocabulary: 'Vocabulary',
    grammar: 'Grammar',
    speaking: 'Speaking',
    listening: 'Listening',
    reading: 'Reading',
    pronunciation: 'Pronunciation',
    flashcards: 'Smart Flashcards',
    slang: 'Real World Slang',
    mediaAnalytics: 'Media Analytics',
    contextCulture: 'Context & Culture',
    pedagogyPartner: 'AI Pedagogy Partner',
    slangCorpus: 'Slang & Corpus Analyzer',
    researchMatrix: 'Research Matrix',
    pedagogyTools: 'Pedagogy Tools',
    thesisTracker: 'Thesis Tracker',
    settings: 'Settings',

    welcomeBack: 'Welcome back',
    keepGoing: "Keep going, you're doing great!",
    dayStreak: 'Day Streak',
    totalXP: 'Total XP',
    level: 'Level',
    wordsLearned: 'Words Learned',
    lessonsComplete: 'Lessons Complete',
    weeklyProgress: 'Weekly Progress',
    todayGoal: "Today's Goal",
    minutesToday: 'minutes today',
    supervisorTasks: "Supervisor's Next Task",
    quickActions: 'Quick Actions',
    startLesson: 'Start Lesson',
    practiceFlash: 'Practice Flashcards',
    dailyChallenge: 'Daily Challenge',

    vocabTitle: 'Build Your Vocabulary',
    vocabSubtitle: "Learn words that matter. Spaced repetition ensures you never forget.",
    newWords: 'New Words',
    review: 'Review',
    mastered: 'Mastered',
    category: 'Category',
    difficulty: 'Difficulty',
    example: 'Example',
    definition: 'Definition',
    addToFlashcards: 'Add to Flashcards',
    nextWord: 'Next Word',
    iKnowThis: 'I Know This',
    showAnswer: 'Show Answer',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',

    grammarTitle: 'Grammar Mastery',
    grammarSubtitle: 'All 16 tenses explained with examples and interactive exercises.',
    tenses: 'Tenses',
    structure: 'Structure',
    usage: 'Usage',
    signalWords: 'Signal Words',
    practice: 'Practice',
    completeLesson: 'Complete Lesson',
    nextTense: 'Next Tense',

    speakingTitle: 'Speaking Practice',
    speakingSubtitle: 'Build confidence speaking English with guided exercises.',
    startRecording: 'Start Recording',
    stopRecording: 'Stop Recording',
    topic: 'Topic',
    duration: 'Duration',

    listeningTitle: 'Listening Lab',
    listeningSubtitle: 'Train your ear with real-world audio content.',
    playAudio: 'Play Audio',
    pauseAudio: 'Pause',
    checkAnswer: 'Check Answer',

    readingTitle: 'Reading Comprehension',
    readingSubtitle: 'Read real articles and build understanding.',
    readMore: 'Read More',
    comprehension: 'Comprehension',

    pronunTitle: 'Pronunciation Coach',
    pronunSubtitle: 'Master English sounds with IPA and audio guides.',
    sounds: 'Sounds',
    practiceIPA: 'Practice IPA',

    flashTitle: 'Smart Flashcards',
    flashSubtitle: 'Spaced repetition powered by SM-2 algorithm. Study smarter, not harder.',
    dueCards: 'Due Cards',
    newCards: 'New Cards',
    totalCards: 'Total Cards',
    again: 'Again',
    hard: 'Hard',
    good: 'Good',
    easy: 'Easy',

    slangTitle: 'Real World Slang',
    slangSubtitle: 'Understand what native speakers actually say.',
    trending: 'Trending',
    formality: 'Formality',

    mediaTitle: 'Media Analytics',
    mediaSubtitle: 'Learn English through movies, songs, and news.',
    movies: 'Movies',
    songs: 'Songs',
    news: 'News',

    cultureTitle: 'Context & Culture',
    cultureSubtitle: 'Language is culture. Understand the why behind the words.',
    scenarios: 'Scenarios',
    culturalNotes: 'Cultural Notes',

    pedTitle: 'AI Pedagogy Partner',
    pedSubtitle: 'Your personal teaching assistant. Ask anything about English.',
    askQuestion: 'Ask a question...',
    send: 'Send',

    continue_: 'Continue',
    back: 'Back',
    next: 'Next',
    save: 'Save',
    cancel: 'Cancel',
    search: 'Search...',
    loading: 'Loading...',
    noResults: 'No results found',
    progress: 'Progress',
    completed: 'Completed',
    start: 'Start',
    score: 'Score',
    correct: 'Correct',
    incorrect: 'Incorrect',
    tryAgain: 'Try Again',
    congratulations: 'Congratulations!',
    translate: 'Translate',
    switchLang: 'Bahasa Indonesia',

    convModeSolo: 'Solo Practice',
    convModeAI: 'AI Conversation',
    convStart: 'Start Conversation',
    convChooseTopic: 'Choose a Topic',
    convApiSettings: 'API Settings',
    convConfigured: 'Configured',
    convProvider: 'Provider',
    convModel: 'Model',
    convApiKey: 'API Key',
    convListening: 'Listening...',
    convSpeaking: 'AI is speaking...',
    convTypeHere: 'Type your response...',
    convEndFeedback: 'End & Get Feedback',
    convFeedback: 'Conversation Feedback',
    convExchanges: 'exchanges',
    convNewConv: 'New Conversation',
    convSpeakBtn: 'Tap to speak',
    convStopSpeak: 'Tap to stop',
  },
  id: {
    dashboard: 'Dasbor',
    vocabulary: 'Kosakata',
    grammar: 'Tata Bahasa',
    speaking: 'Berbicara',
    listening: 'Mendengarkan',
    reading: 'Membaca',
    pronunciation: 'Pengucapan',
    flashcards: 'Kartu Pintar',
    slang: 'Bahasa Gaul',
    mediaAnalytics: 'Analisis Media',
    contextCulture: 'Konteks & Budaya',
    pedagogyPartner: 'Mitra Pedagogi AI',
    slangCorpus: 'Penganalisis Bahasa Gaul',
    researchMatrix: 'Matriks Riset',
    pedagogyTools: 'Alat Pedagogi',
    thesisTracker: 'Pelacak Skripsi',
    settings: 'Pengaturan',

    welcomeBack: 'Selamat datang kembali',
    keepGoing: 'Terus semangat, kamu hebat!',
    dayStreak: 'Hari Berturut',
    totalXP: 'Total XP',
    level: 'Level',
    wordsLearned: 'Kata Dipelajari',
    lessonsComplete: 'Pelajaran Selesai',
    weeklyProgress: 'Progres Mingguan',
    todayGoal: 'Target Hari Ini',
    minutesToday: 'menit hari ini',
    supervisorTasks: 'Tugas Pengawas Berikutnya',
    quickActions: 'Aksi Cepat',
    startLesson: 'Mulai Pelajaran',
    practiceFlash: 'Latihan Kartu',
    dailyChallenge: 'Tantangan Harian',

    vocabTitle: 'Perluas Kosakatamu',
    vocabSubtitle: 'Pelajari kata-kata penting. Pengulangan berjarak memastikan kamu tidak lupa.',
    newWords: 'Kata Baru',
    review: 'Ulang',
    mastered: 'Dikuasai',
    category: 'Kategori',
    difficulty: 'Kesulitan',
    example: 'Contoh',
    definition: 'Definisi',
    addToFlashcards: 'Tambah ke Kartu',
    nextWord: 'Kata Berikutnya',
    iKnowThis: 'Saya Tahu',
    showAnswer: 'Tunjukkan Jawaban',
    beginner: 'Pemula',
    intermediate: 'Menengah',
    advanced: 'Lanjutan',

    grammarTitle: 'Kuasai Tata Bahasa',
    grammarSubtitle: 'Semua 16 tenses dijelasin dengan contoh dan latihan interaktif.',
    tenses: 'Tenses',
    structure: 'Struktur',
    usage: 'Penggunaan',
    signalWords: 'Kata Sinyal',
    practice: 'Latihan',
    completeLesson: 'Selesaikan Pelajaran',
    nextTense: 'Tense Berikutnya',

    speakingTitle: 'Latihan Bicara',
    speakingSubtitle: 'Bangun kepercayaan diri berbicara bahasa Inggris.',
    startRecording: 'Mulai Rekam',
    stopRecording: 'Stop Rekam',
    topic: 'Topik',
    duration: 'Durasi',

    listeningTitle: 'Lab Mendengarkan',
    listeningSubtitle: 'Latih pendengaranmu dengan audio dunia nyata.',
    playAudio: 'Putar Audio',
    pauseAudio: 'Jeda',
    checkAnswer: 'Cek Jawaban',

    readingTitle: 'Pemahaman Membaca',
    readingSubtitle: 'Baca artikel nyata dan bangun pemahaman.',
    readMore: 'Baca Selengkapnya',
    comprehension: 'Pemahaman',

    pronunTitle: 'Pelatih Pengucapan',
    pronunSubtitle: 'Kuasai bunyi bahasa Inggris dengan panduan IPA dan audio.',
    sounds: 'Bunyi',
    practiceIPA: 'Latihan IPA',

    flashTitle: 'Kartu Pintar',
    flashSubtitle: 'Pengulangan berjarak dengan algoritma SM-2. Belajar lebih cerdas.',
    dueCards: 'Kartu Jatuh Tempo',
    newCards: 'Kartu Baru',
    totalCards: 'Total Kartu',
    again: 'Ulang',
    hard: 'Sulit',
    good: 'Bagus',
    easy: 'Mudah',

    slangTitle: 'Bahasa Gaul Nyata',
    slangSubtitle: 'Pahami apa yang penutur asli sebenarnya katakan.',
    trending: 'Trending',
    formality: 'Formalitas',

    mediaTitle: 'Analisis Media',
    mediaSubtitle: 'Belajar bahasa Inggris lewat film, lagu, dan berita.',
    movies: 'Film',
    songs: 'Lagu',
    news: 'Berita',

    cultureTitle: 'Konteks & Budaya',
    cultureSubtitle: 'Bahasa adalah budaya. Pahami kenapa di balik kata-kata.',
    scenarios: 'Skenario',
    culturalNotes: 'Catatan Budaya',

    pedTitle: 'Mitra Pedagogi AI',
    pedSubtitle: 'Asisten pengajar pribadimu. Tanya apa saja tentang bahasa Inggris.',
    askQuestion: 'Tanyakan sesuatu...',
    send: 'Kirim',

    continue_: 'Lanjut',
    back: 'Kembali',
    next: 'Selanjutnya',
    save: 'Simpan',
    cancel: 'Batal',
    search: 'Cari...',
    loading: 'Memuat...',
    noResults: 'Tidak ada hasil',
    progress: 'Progres',
    completed: 'Selesai',
    start: 'Mulai',
    score: 'Skor',
    correct: 'Benar',
    incorrect: 'Salah',
    tryAgain: 'Coba Lagi',
    congratulations: 'Selamat!',
    translate: 'Terjemahkan',
    switchLang: 'English',

    convModeSolo: 'Latihan Sendiri',
    convModeAI: 'Percakapan AI',
    convStart: 'Mulai Percakapan',
    convChooseTopic: 'Pilih Topik',
    convApiSettings: 'Pengaturan API',
    convConfigured: 'Terkonfigurasi',
    convProvider: 'Penyedia',
    convModel: 'Model',
    convApiKey: 'Kunci API',
    convListening: 'Mendengarkan...',
    convSpeaking: 'AI sedang berbicara...',
    convTypeHere: 'Ketik jawabanmu...',
    convEndFeedback: 'Selesai & Dapat Feedback',
    convFeedback: 'Feedback Percakapan',
    convExchanges: 'percakapan',
    convNewConv: 'Percakapan Baru',
    convSpeakBtn: 'Tekan untuk bicara',
    convStopSpeak: 'Tekan untuk berhenti',
  }
}

const useLangStore = create((set, get) => ({
  lang: localStorage.getItem("appLang") || "id",
  t: (key) => translations[get().lang][key] || key,
  toggleLang: () => set((state) => {
    const newLang = state.lang === "en" ? "id" : "en"
    localStorage.setItem("appLang", newLang)
    return { lang: newLang }
  }),
  setLang: (lang) => {
    localStorage.setItem("appLang", lang)
    set({ lang })
  }
}))

export default useLangStore
